baseURL = "/"
title = "Dust Data Management"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
image = "banner.jpg"

[params]
fancyTitle = "Dust Data Management" # title for frontpage, may include image
copyright = "Taylor Johnson"
description = 'So you can focus on the science'
#startbuttonText = "Activate"
#startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Services'
body = '''
DDM provides digital data resource management and archival solutions for planetary missions.\
\
\
*Current projects:*\
Sample Analysis Micro-Information System (SAMIS)\
Origins, Spectral Interpretation, Resource Identification, Security-Regolith Explorer (OSIRIS-REx)
'''

[[params.one.icon]]
icon = "fa-rocket"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-database"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-connectdevelop"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "images/image1_resized.png"
title = 'Taylor Johnson, MLIS'
body = '''
Taylor Johnson (she/her) has a rich professional history in complex data description and
organization results in high-quality archival results. With over ten
years of experience in libraries, Taylor enjoys working closely with
data providers to ensure long-term preservation and interoperability
of digitized and born-digital institutional assets. She is passionate
about open access, equity, and data reuse.


Good data stewardship is about understanding the whole picture;
from point of creation to retrieval. With this in mind, Taylor is
committed to providing you with a reliable product, so you can focus
on the science.
'''

[params.three]
enable = false
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-headphones"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = true
title = 'Contact'
body = '''
Taylor Johnson, MLIS (she/her)\
Digital Data Librarian and Archivist


**Phone**: 520 200 1707\
**Email**: taylor@dustdatamgmt.com
'''

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"
